Modify bash script

diff --git a/fuz-donwloader b/fuz-donwloader
--- a/fuz-donwloader
+++ b/fuz-donwloader
@@ -4,18 +4,49 @@ SRC_URL="https://github.com/Kumaizep/Fuz-Downloader/archive/refs/heads/main.zip"
 SRC_ZIP="main.zip"
 SRC_DIR="Fuz-Downloader-main"
 
+Vercomp () {
+    if [[ $1 == $2 ]]
+    then
+        return 0
+    fi
+    local IFS=.
+    local i ver1=($1) ver2=($2)
+    # fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+    do
+        ver1[i]=0
+    done
+    for ((i=0; i<${#ver1[@]}; i++))
+    do
+        if [[ -z ${ver2[i]} ]]
+        then
+            # fill empty fields in ver2 with zeros
+            ver2[i]=0
+        fi
+        if ((10#${ver1[i]} > 10#${ver2[i]}))
+        then
+            return 1
+        fi
+        if ((10#${ver1[i]} < 10#${ver2[i]}))
+        then
+            return 2
+        fi
+    done
+    return 0
+}
+
 Install () {
     currentver="$(python3 -V | cut -d" " -f2)"
     requiredver="3.10.0"
 
-    if ! [ command -v poetry &> /dev/null ]; then
+    if ! command -v poetry &> /dev/null; then
         echo "[#] Poetry not found"
-        if ! [ command -v python &> /dev/null ]; then
-            echo "Could not find python or the version is too old."
+        if ! command -v python3 &> /dev/null; then
+            echo "Could not find python"
             exit
-        elif [ "$(printf '%s\n' "$requiredver" "$currentver" | sort -V | head -n1)" = "$requiredver" ]; then
-            echo "Could not find python or the version is too old."
-            exit
+        # elif [ "$(printf '%s\n' "$requiredver" "$currentver" | sort -V | head -n1)" = "$requiredver" ]; then
+        #     echo "python version is too old."
+        #     exit
         fi
         echo "[#] Try to install poetry"
         curl -sSL https://install.python-poetry.org | python3 -
